# Generated by Django 3.2.3 on 2021-09-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adminpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=150, verbose_name='Instagram')),
                ('twitter', models.CharField(max_length=150, verbose_name='twitter')),
                ('linkedin', models.CharField(max_length=150, verbose_name='linkedin')),
                ('facebook', models.CharField(max_length=150, verbose_name='facebook')),
                ('whatsapp', models.CharField(max_length=150, verbose_name='watsapp')),
            ],
        ),
    ]
