# Generated by Django 3.2.3 on 2021-09-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210912_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
        migrations.AddField(
            model_name='adminpage',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='İcon'),
        ),
        migrations.AddField(
            model_name='adminpage',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Şəkil'),
        ),
    ]
