# Generated by Django 3.2.3 on 2021-09-13 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210913_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpage',
            name='whatsapp_image',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Whatsapp'),
        ),
    ]
